when:
  - event: push
    branch: master
  - event: cron
    cron: "daily build"

steps:
  - when:
      - event: pull_request
    name: build container
    image: plugins/kaniko
    settings:
      dry-run: true
      dockerfile: Containerfile

  - when:
      - evaluate: 'CI_COMMIT_BRANCH == CI_REPO_DEFAULT_BRANCH'
    name: build and publish container
    image: plugins/kaniko
    settings:
      registry: https://registry.fuwafuwatime.moe
      repo: registry.fuwafuwatime.moe/concord/minecraft-pdb-mgr
      dockerfile: Containerfile
      tags:
        - latest
        - ${CI_COMMIT_TAG:-${CI_COMMIT_SHA:0:8}}
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
